// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDV_6WvaVcIzVT7lxVQNZPT-ZFQrfeqZ0',
    appId: '1:786002762040:web:f1f1725e8b28c64d2e49cd',
    messagingSenderId: '786002762040',
    projectId: 'online-shopping-app-c06eb',
    authDomain: 'online-shopping-app-c06eb.firebaseapp.com',
    storageBucket: 'online-shopping-app-c06eb.firebasestorage.app',
    measurementId: 'G-ZTKJR1GL7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQTnKoxUEvASS-aTPcC-G_DgdyufeZv5w',
    appId: '1:786002762040:android:babbc4ce05a5d4762e49cd',
    messagingSenderId: '786002762040',
    projectId: 'online-shopping-app-c06eb',
    storageBucket: 'online-shopping-app-c06eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUsBHUdjZVX-_rROv6T3DyvVXIfm7DA4',
    appId: '1:786002762040:ios:82a7186566bdd35f2e49cd',
    messagingSenderId: '786002762040',
    projectId: 'online-shopping-app-c06eb',
    storageBucket: 'online-shopping-app-c06eb.firebasestorage.app',
    iosBundleId: 'com.example.onlineshoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUsBHUdjZVX-_rROv6T3DyvVXIfm7DA4',
    appId: '1:786002762040:ios:82a7186566bdd35f2e49cd',
    messagingSenderId: '786002762040',
    projectId: 'online-shopping-app-c06eb',
    storageBucket: 'online-shopping-app-c06eb.firebasestorage.app',
    iosBundleId: 'com.example.onlineshoppingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDV_6WvaVcIzVT7lxVQNZPT-ZFQrfeqZ0',
    appId: '1:786002762040:web:4a6d4feae28050362e49cd',
    messagingSenderId: '786002762040',
    projectId: 'online-shopping-app-c06eb',
    authDomain: 'online-shopping-app-c06eb.firebaseapp.com',
    storageBucket: 'online-shopping-app-c06eb.firebasestorage.app',
    measurementId: 'G-EJGRM45YDK',
  );
}
